grep '^chr1' restr_enzyme_sites.txt  > chr1_restr_enzyme_sites.txt 
grep '^chr2' restr_enzyme_sites.txt  > chr2_restr_enzyme_sites.txt 
grep '^chr3' restr_enzyme_sites.txt  > chr3_restr_enzyme_sites.txt 
grep '^chr4' restr_enzyme_sites.txt  > chr4_restr_enzyme_sites.txt 
grep '^chr5' restr_enzyme_sites.txt  > chr5_restr_enzyme_sites.txt 
grep '^chr6' restr_enzyme_sites.txt  > chr6_restr_enzyme_sites.txt 
grep '^chr7' restr_enzyme_sites.txt  > chr7_restr_enzyme_sites.txt 
grep '^chr8' restr_enzyme_sites.txt  > chr8_restr_enzyme_sites.txt 
grep '^chr9' restr_enzyme_sites.txt  > chr9_restr_enzyme_sites.txt 
grep '^chr10' restr_enzyme_sites.txt  > chr10_restr_enzyme_sites.txt 
grep '^chr11' restr_enzyme_sites.txt  > chr11_restr_enzyme_sites.txt 
grep '^chr12' restr_enzyme_sites.txt  > chr12_restr_enzyme_sites.txt 
grep '^chr13' restr_enzyme_sites.txt  > chr13_restr_enzyme_sites.txt 
grep '^chr14' restr_enzyme_sites.txt  > chr14_restr_enzyme_sites.txt 
grep '^chr15' restr_enzyme_sites.txt  > chr15_restr_enzyme_sites.txt 
grep '^chr16' restr_enzyme_sites.txt  > chr16_restr_enzyme_sites.txt 
grep '^chr17' restr_enzyme_sites.txt  > chr17_restr_enzyme_sites.txt 
grep '^chr18' restr_enzyme_sites.txt  > chr18_restr_enzyme_sites.txt 
grep '^chr19' restr_enzyme_sites.txt  > chr19_restr_enzyme_sites.txt 
grep '^chrM' restr_enzyme_sites.txt  > chrM_restr_enzyme_sites.txt 
grep '^chrX' restr_enzyme_sites.txt  > chrX_restr_enzyme_sites.txt 
grep '^chrY' restr_enzyme_sites.txt  > chrY_restr_enzyme_sites.txt 
