cd /lustre1/mz00685/mice_alignment/x_coverage/3x_cov/
grep -w '^chr1' 3x_coverage_stats.txt  > chr1_3x_cov.txt
grep -w '^chr2' 3x_coverage_stats.txt  > chr2_3x_cov.txt
grep -w '^chr3' 3x_coverage_stats.txt  > chr3_3x_cov.txt
grep -w '^chr4' 3x_coverage_stats.txt  > chr4_3x_cov.txt
grep -w '^chr5' 3x_coverage_stats.txt  > chr5_3x_cov.txt
grep -w '^chr6' 3x_coverage_stats.txt  > chr6_3x_cov.txt
grep -w '^chr7' 3x_coverage_stats.txt  > chr7_3x_cov.txt
grep -w '^chr8' 3x_coverage_stats.txt  > chr8_3x_cov.txt
grep -w '^chr9' 3x_coverage_stats.txt  > chr9_3x_cov.txt
grep -w '^chr10' 3x_coverage_stats.txt  > chr10_3x_cov.txt
grep -w '^chr11' 3x_coverage_stats.txt  > chr11_3x_cov.txt
grep -w '^chr12' 3x_coverage_stats.txt  > chr12_3x_cov.txt
grep -w '^chr13' 3x_coverage_stats.txt  > chr13_3x_cov.txt
grep -w '^chr14' 3x_coverage_stats.txt  > chr14_3x_cov.txt
grep -w '^chr15' 3x_coverage_stats.txt  > chr15_3x_cov.txt
grep -w '^chr16' 3x_coverage_stats.txt  > chr16_3x_cov.txt
grep -w '^chr17' 3x_coverage_stats.txt  > chr17_3x_cov.txt
grep -w '^chr18' 3x_coverage_stats.txt  > chr18_3x_cov.txt
grep -w '^chr19' 3x_coverage_stats.txt  > chr19_3x_cov.txt
grep -w '^chrM' 3x_coverage_stats.txt  > chrM_3x_cov.txt
grep -w '^chrX' 3x_coverage_stats.txt  > chrX_3x_cov.txt
grep -w '^chrY' 3x_coverage_stats.txt  > chrY_3x_cov.txt
