cd /Users/madisonzwink/Desktop/GBS_project/demultiplex/
cat chr1.fa.gz >> mm9_genome.fa.gz
cat chr2.fa.gz >> mm9_genome.fa.gz
cat chr3.fa.gz >> mm9_genome.fa.gz
cat chr4.fa.gz >> mm9_genome.fa.gz
cat chr5.fa.gz >> mm9_genome.fa.gz
cat chr6.fa.gz >> mm9_genome.fa.gz
cat chr7.fa.gz >> mm9_genome.fa.gz
cat chr8.fa.gz >> mm9_genome.fa.gz
cat chr9.fa.gz >> mm9_genome.fa.gz
cat chr10.fa.gz >> mm9_genome.fa.gz
cat chr11.fa.gz >> mm9_genome.fa.gz
cat chr12.fa.gz >> mm9_genome.fa.gz
cat chr13.fa.gz >> mm9_genome.fa.gz
cat chr14.fa.gz >> mm9_genome.fa.gz
cat chr15.fa.gz >> mm9_genome.fa.gz
cat chr16.fa.gz >> mm9_genome.fa.gz
cat chr17.fa.gz >> mm9_genome.fa.gz
cat chr18.fa.gz >> mm9_genome.fa.gz
cat chr19.fa.gz >> mm9_genome.fa.gz
cat chrX.fa.gz >> mm9_genome.fa.gz
cat chrY.fa.gz >> mm9_genome.fa.gz
