cd /Users/madisonzwink/Desktop/GBS_project/demultiplex/
touch chr1_snp_counts_dict.py
touch chr2_snp_counts_dict.py
touch chr3_snp_counts_dict.py
touch chr4_snp_counts_dict.py
touch chr5_snp_counts_dict.py
touch chr6_snp_counts_dict.py
touch chr7_snp_counts_dict.py
touch chr8_snp_counts_dict.py
touch chr9_snp_counts_dict.py
touch chr10_snp_counts_dict.py
touch chr11_snp_counts_dict.py
touch chr12_snp_counts_dict.py
touch chr13_snp_counts_dict.py
touch chr14_snp_counts_dict.py
touch chr15_snp_counts_dict.py
touch chr16_snp_counts_dict.py
touch chr17_snp_counts_dict.py
touch chr18_snp_counts_dict.py
touch chr19_snp_counts_dict.py
touch chrM_snp_counts_dict.py
touch chrX_snp_counts_dict.py
touch chrY_snp_counts_dict.py
